package pdf

import "testing"

// The "qs" field expands the base64 download URLs whose options are otherwise
// unreadable in the log -- the /v4/ protobuf and the /v2/h/ query string -- but
// not the classic /hebcal/index.cgi/ form, which carries its query in the URL.
func TestIsOpaquePath(t *testing.T) {
	cases := map[string]bool{
		"/v4/QAFIAWCbLfgDAQ/hebcal_5787h.pdf": true,
		"/v2/h/dj0xJnllYXI9MjAyMQ/hebcal.pdf": true,
		"/hebcal/index.cgi/hebcal.pdf":        false,
	}
	for path, want := range cases {
		if got := isOpaquePath(path); got != want {
			t.Errorf("isOpaquePath(%q) = %v, want %v", path, got, want)
		}
	}
}

// MessageToQuery renders a decoded Download protobuf back into the query string
// hebcal-web's deserializeDownload.js produces from the same message. The
// expected values below were generated by running downloadHref2() to encode
// each query and deserializeDownload() to decode it (its keys url-encoded with
// encodeURIComponent), so they are hebcal-web's own output byte-for-byte. Keep
// this in step with deserializeDownload.js: it is the log's window onto an
// otherwise opaque /v4/<base64> URL.
func TestMessageToQuery(t *testing.T) {
	cases := []struct {
		name    string
		payload string
		want    string
	}{
		{
			// The kitzur-shulchan-aruch Hebrew-year calendar from the bug report.
			"hebrew year, unsupported learning",
			"QAFIAWCbLfgDAQ",
			"v=1&M=on&yt=H&year=5787&lg=s&dksa=on&mm=0",
		},
		{
			"holidays, location, havdalah minutes",
			"CAEQARgBIAEoATABUAFY97zSAWDqD2oBc3AyeBKAAQE",
			"v=1&maj=on&min=on&nx=on&mod=on&mf=on&ss=on&M=off&m=50&yt=G&c=on&" +
				"geonameid=3448439&year=2026&lg=s&b=18&emoji=1&mm=0",
		},
		{
			"year=now, Israel, Hebrew month mode, sedrot",
			"OAFAAWoCaGWIAQGYAQHQAQHgAQHoAwGABAE",
			"v=1&i=on&M=on&yt=G&year=now&lg=he&F=on&myomi=on&dr3=on&s=on&mm=1",
		},
		{
			"euro, 24-hour, multi-year, zip, alt dates",
			"YOsPkgEFOTQzMDOgAQG4AQHAAQHIAQHYAQHwAQX4AQOoAgG4AgKoAwHAAwHgAwGIBAE",
			"v=1&M=off&m=0&yt=G&year=2027&lg=s&euro=1&h12=0&subscribe=1&ny=3&" +
				"zip=94303&o=on&d=on&D=on&ykk=on&ue=on&yzkr=on&mvch=on&mm=0&yto=on&month=5",
		},
		{
			"lat/long location with elevation and typeahead name",
			"QAFQAWDqD-gBAc0CgcQVQtUCN0n0wpICE0FtZXJpY2EvTG9zX0FuZ2VsZXPCAglQYWxvIEFsdG-gAwo",
			"v=1&M=on&yt=G&c=on&year=2026&lg=s&mm=0&latitude=37.441898345947266&" +
				"longitude=-122.14299774169922&elev=10&city-typeahead=Palo%20Alto&" +
				"geo=pos&tzid=America%2FLos_Angeles",
		},
		{
			"start/end date range",
			"CAFAAdgCgNPYygbgAvDhrc4G",
			"v=1&maj=on&M=on&yt=G&lg=s&mm=0&start=2026-01-01&end=2026-03-31",
		},
		{
			"the six unsupported learning series",
			"QAFg6g-4AgGAAwGIAwHIAwHwAwGQBAE",
			"v=1&M=on&yt=G&year=2026&lg=s&h12=1&dsm=on&dcc=on&dshl=on&ayd=on&ahsy=on&mm=0",
		},
		{
			"the remaining daily-learning series",
			"QAFg6g_oAgHwAgH4AgGQAwGYAwGwAwG4AwHQAwHYAwGABAKgBAE",
			"v=1&M=on&yt=G&year=2026&lg=s&dpy=on&nyomi=on&dty=on&dps=on&d929=on&" +
				"dr1=on&yyomi=on&yys=on&dw=on&dpa=on&mm=2",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			msg, err := DecodeMessage(tc.payload)
			if err != nil {
				t.Fatalf("DecodeMessage(%q): %v", tc.payload, err)
			}
			if got := MessageToQuery(msg); got != tc.want {
				t.Errorf("MessageToQuery =\n  %s\nwant\n  %s", got, tc.want)
			}
		})
	}
}
