// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: download.proto

package downloadpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Download_Hour12 int32

const (
	Download_UNSET Download_Hour12 = 0
	Download_ON    Download_Hour12 = 1
	Download_OFF   Download_Hour12 = 2
)

// Enum value maps for Download_Hour12.
var (
	Download_Hour12_name = map[int32]string{
		0: "UNSET",
		1: "ON",
		2: "OFF",
	}
	Download_Hour12_value = map[string]int32{
		"UNSET": 0,
		"ON":    1,
		"OFF":   2,
	}
)

func (x Download_Hour12) Enum() *Download_Hour12 {
	p := new(Download_Hour12)
	*p = x
	return p
}

func (x Download_Hour12) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Download_Hour12) Descriptor() protoreflect.EnumDescriptor {
	return file_download_proto_enumTypes[0].Descriptor()
}

func (Download_Hour12) Type() protoreflect.EnumType {
	return &file_download_proto_enumTypes[0]
}

func (x Download_Hour12) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Download_Hour12.Descriptor instead.
func (Download_Hour12) EnumDescriptor() ([]byte, []int) {
	return file_download_proto_rawDescGZIP(), []int{0, 0}
}

type Download_MonthMode int32

const (
	Download_GREGORIAN_ARABIC Download_MonthMode = 0
	Download_HEBREW_ARABIC    Download_MonthMode = 1
	Download_HEBREW_HEBREW    Download_MonthMode = 2
)

// Enum value maps for Download_MonthMode.
var (
	Download_MonthMode_name = map[int32]string{
		0: "GREGORIAN_ARABIC",
		1: "HEBREW_ARABIC",
		2: "HEBREW_HEBREW",
	}
	Download_MonthMode_value = map[string]int32{
		"GREGORIAN_ARABIC": 0,
		"HEBREW_ARABIC":    1,
		"HEBREW_HEBREW":    2,
	}
)

func (x Download_MonthMode) Enum() *Download_MonthMode {
	p := new(Download_MonthMode)
	*p = x
	return p
}

func (x Download_MonthMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Download_MonthMode) Descriptor() protoreflect.EnumDescriptor {
	return file_download_proto_enumTypes[1].Descriptor()
}

func (Download_MonthMode) Type() protoreflect.EnumType {
	return &file_download_proto_enumTypes[1]
}

func (x Download_MonthMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Download_MonthMode.Descriptor instead.
func (Download_MonthMode) EnumDescriptor() ([]byte, []int) {
	return file_download_proto_rawDescGZIP(), []int{0, 1}
}

type Download struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Major                bool                   `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor                bool                   `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	RoshChodesh          bool                   `protobuf:"varint,3,opt,name=roshChodesh,proto3" json:"roshChodesh,omitempty"`
	Modern               bool                   `protobuf:"varint,4,opt,name=modern,proto3" json:"modern,omitempty"`
	MinorFast            bool                   `protobuf:"varint,5,opt,name=minorFast,proto3" json:"minorFast,omitempty"`
	SpecialShabbat       bool                   `protobuf:"varint,6,opt,name=specialShabbat,proto3" json:"specialShabbat,omitempty"`
	Israel               bool                   `protobuf:"varint,7,opt,name=israel,proto3" json:"israel,omitempty"`
	HavdalahTzeit        bool                   `protobuf:"varint,8,opt,name=havdalahTzeit,proto3" json:"havdalahTzeit,omitempty"`
	IsHebrewYear         bool                   `protobuf:"varint,9,opt,name=isHebrewYear,proto3" json:"isHebrewYear,omitempty"`
	Candlelighting       bool                   `protobuf:"varint,10,opt,name=candlelighting,proto3" json:"candlelighting,omitempty"`
	Geonameid            int32                  `protobuf:"varint,11,opt,name=geonameid,proto3" json:"geonameid,omitempty"`
	Year                 int32                  `protobuf:"varint,12,opt,name=year,proto3" json:"year,omitempty"`
	Locale               string                 `protobuf:"bytes,13,opt,name=locale,proto3" json:"locale,omitempty"`
	HavdalahMins         int32                  `protobuf:"varint,14,opt,name=havdalahMins,proto3" json:"havdalahMins,omitempty"`
	CandleLightingMins   int32                  `protobuf:"varint,15,opt,name=candleLightingMins,proto3" json:"candleLightingMins,omitempty"`
	Emoji                bool                   `protobuf:"varint,16,opt,name=emoji,proto3" json:"emoji,omitempty"`
	Sedrot               bool                   `protobuf:"varint,17,opt,name=sedrot,proto3" json:"sedrot,omitempty"`
	Zip                  string                 `protobuf:"bytes,18,opt,name=zip,proto3" json:"zip,omitempty"`
	YearNow              bool                   `protobuf:"varint,19,opt,name=yearNow,proto3" json:"yearNow,omitempty"`
	Subscribe            bool                   `protobuf:"varint,20,opt,name=subscribe,proto3" json:"subscribe,omitempty"`
	AddAltDates          bool                   `protobuf:"varint,23,opt,name=addAltDates,proto3" json:"addAltDates,omitempty"`
	AddAltDatesForEvents bool                   `protobuf:"varint,24,opt,name=addAltDatesForEvents,proto3" json:"addAltDatesForEvents,omitempty"`
	Omer                 bool                   `protobuf:"varint,25,opt,name=omer,proto3" json:"omer,omitempty"`
	Dafyomi              bool                   `protobuf:"varint,26,opt,name=dafyomi,proto3" json:"dafyomi,omitempty"`
	Euro                 bool                   `protobuf:"varint,27,opt,name=euro,proto3" json:"euro,omitempty"`
	MishnaYomi           bool                   `protobuf:"varint,28,opt,name=mishnaYomi,proto3" json:"mishnaYomi,omitempty"`
	GeoPos               bool                   `protobuf:"varint,29,opt,name=geoPos,proto3" json:"geoPos,omitempty"`
	Month                int32                  `protobuf:"varint,30,opt,name=month,proto3" json:"month,omitempty"`
	NumYears             int32                  `protobuf:"varint,31,opt,name=numYears,proto3" json:"numYears,omitempty"`
	// Types that are valid to be assigned to LatOneof:
	//
	//	*Download_OldLatitude
	//	*Download_Latitude
	LatOneof isDownload_LatOneof `protobuf_oneof:"lat_oneof"`
	// Types that are valid to be assigned to LongOneof:
	//
	//	*Download_OldLongitude
	//	*Download_Longitude
	LongOneof isDownload_LongOneof `protobuf_oneof:"long_oneof"`
	Tzid      string               `protobuf:"bytes,34,opt,name=tzid,proto3" json:"tzid,omitempty"`
	// Types that are valid to be assigned to StartOneof:
	//
	//	*Download_StartStr
	//	*Download_Start
	StartOneof isDownload_StartOneof `protobuf_oneof:"start_oneof"`
	// Types that are valid to be assigned to EndOneof:
	//
	//	*Download_EndStr
	//	*Download_End
	EndOneof            isDownload_EndOneof `protobuf_oneof:"end_oneof"`
	YomKippurKatan      bool                `protobuf:"varint,37,opt,name=yomKippurKatan,proto3" json:"yomKippurKatan,omitempty"`
	Hour12              Download_Hour12     `protobuf:"varint,39,opt,name=hour12,proto3,enum=Download_Hour12" json:"hour12,omitempty"`
	CityName            string              `protobuf:"bytes,40,opt,name=cityName,proto3" json:"cityName,omitempty"`
	YerushalmiYomi      bool                `protobuf:"varint,45,opt,name=yerushalmiYomi,proto3" json:"yerushalmiYomi,omitempty"`
	NachYomi            bool                `protobuf:"varint,46,opt,name=nachYomi,proto3" json:"nachYomi,omitempty"`
	Rambam1             bool                `protobuf:"varint,47,opt,name=rambam1,proto3" json:"rambam1,omitempty"`
	ChofetzChaim        bool                `protobuf:"varint,48,opt,name=chofetzChaim,proto3" json:"chofetzChaim,omitempty"`
	ShemiratHaLashon    bool                `protobuf:"varint,49,opt,name=shemiratHaLashon,proto3" json:"shemiratHaLashon,omitempty"`
	Psalms              bool                `protobuf:"varint,50,opt,name=psalms,proto3" json:"psalms,omitempty"`
	DafWeekly           bool                `protobuf:"varint,51,opt,name=dafWeekly,proto3" json:"dafWeekly,omitempty"`
	Elev                int32               `protobuf:"varint,52,opt,name=elev,proto3" json:"elev,omitempty"`
	UseElevation        bool                `protobuf:"varint,53,opt,name=useElevation,proto3" json:"useElevation,omitempty"`
	TanakhYomi          bool                `protobuf:"varint,54,opt,name=tanakhYomi,proto3" json:"tanakhYomi,omitempty"`
	PirkeiAvotSummer    bool                `protobuf:"varint,55,opt,name=pirkeiAvotSummer,proto3" json:"pirkeiAvotSummer,omitempty"`
	Yizkor              bool                `protobuf:"varint,56,opt,name=yizkor,proto3" json:"yizkor,omitempty"`
	ArukhHaShulchanYomi bool                `protobuf:"varint,57,opt,name=arukhHaShulchanYomi,proto3" json:"arukhHaShulchanYomi,omitempty"`
	YySchottenstein     bool                `protobuf:"varint,58,opt,name=yySchottenstein,proto3" json:"yySchottenstein,omitempty"`
	PerekYomi           bool                `protobuf:"varint,59,opt,name=perekYomi,proto3" json:"perekYomi,omitempty"`
	ShabbatMevarchim    bool                `protobuf:"varint,60,opt,name=shabbatMevarchim,proto3" json:"shabbatMevarchim,omitempty"`
	Rambam3             bool                `protobuf:"varint,61,opt,name=rambam3,proto3" json:"rambam3,omitempty"`
	SeferHaMitzvot      bool                `protobuf:"varint,62,opt,name=seferHaMitzvot,proto3" json:"seferHaMitzvot,omitempty"`
	KitzurShulchanAruch bool                `protobuf:"varint,63,opt,name=kitzurShulchanAruch,proto3" json:"kitzurShulchanAruch,omitempty"`
	MonthMode           Download_MonthMode  `protobuf:"varint,64,opt,name=monthMode,proto3,enum=Download_MonthMode" json:"monthMode,omitempty"`
	YomTovOnly          bool                `protobuf:"varint,65,opt,name=yomTovOnly,proto3" json:"yomTovOnly,omitempty"`
	DirshuAmudYomi      bool                `protobuf:"varint,66,opt,name=dirshuAmudYomi,proto3" json:"dirshuAmudYomi,omitempty"`
	Tzeit               float32             `protobuf:"fixed32,67,opt,name=tzeit,proto3" json:"tzeit,omitempty"`
	Nine29              bool                `protobuf:"varint,68,opt,name=nine29,proto3" json:"nine29,omitempty"`
	DirshuDafHalacha    bool                `protobuf:"varint,69,opt,name=dirshuDafHalacha,proto3" json:"dirshuDafHalacha,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Download) Reset() {
	*x = Download{}
	mi := &file_download_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Download) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Download) ProtoMessage() {}

func (x *Download) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Download.ProtoReflect.Descriptor instead.
func (*Download) Descriptor() ([]byte, []int) {
	return file_download_proto_rawDescGZIP(), []int{0}
}

func (x *Download) GetMajor() bool {
	if x != nil {
		return x.Major
	}
	return false
}

func (x *Download) GetMinor() bool {
	if x != nil {
		return x.Minor
	}
	return false
}

func (x *Download) GetRoshChodesh() bool {
	if x != nil {
		return x.RoshChodesh
	}
	return false
}

func (x *Download) GetModern() bool {
	if x != nil {
		return x.Modern
	}
	return false
}

func (x *Download) GetMinorFast() bool {
	if x != nil {
		return x.MinorFast
	}
	return false
}

func (x *Download) GetSpecialShabbat() bool {
	if x != nil {
		return x.SpecialShabbat
	}
	return false
}

func (x *Download) GetIsrael() bool {
	if x != nil {
		return x.Israel
	}
	return false
}

func (x *Download) GetHavdalahTzeit() bool {
	if x != nil {
		return x.HavdalahTzeit
	}
	return false
}

func (x *Download) GetIsHebrewYear() bool {
	if x != nil {
		return x.IsHebrewYear
	}
	return false
}

func (x *Download) GetCandlelighting() bool {
	if x != nil {
		return x.Candlelighting
	}
	return false
}

func (x *Download) GetGeonameid() int32 {
	if x != nil {
		return x.Geonameid
	}
	return 0
}

func (x *Download) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Download) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *Download) GetHavdalahMins() int32 {
	if x != nil {
		return x.HavdalahMins
	}
	return 0
}

func (x *Download) GetCandleLightingMins() int32 {
	if x != nil {
		return x.CandleLightingMins
	}
	return 0
}

func (x *Download) GetEmoji() bool {
	if x != nil {
		return x.Emoji
	}
	return false
}

func (x *Download) GetSedrot() bool {
	if x != nil {
		return x.Sedrot
	}
	return false
}

func (x *Download) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

func (x *Download) GetYearNow() bool {
	if x != nil {
		return x.YearNow
	}
	return false
}

func (x *Download) GetSubscribe() bool {
	if x != nil {
		return x.Subscribe
	}
	return false
}

func (x *Download) GetAddAltDates() bool {
	if x != nil {
		return x.AddAltDates
	}
	return false
}

func (x *Download) GetAddAltDatesForEvents() bool {
	if x != nil {
		return x.AddAltDatesForEvents
	}
	return false
}

func (x *Download) GetOmer() bool {
	if x != nil {
		return x.Omer
	}
	return false
}

func (x *Download) GetDafyomi() bool {
	if x != nil {
		return x.Dafyomi
	}
	return false
}

func (x *Download) GetEuro() bool {
	if x != nil {
		return x.Euro
	}
	return false
}

func (x *Download) GetMishnaYomi() bool {
	if x != nil {
		return x.MishnaYomi
	}
	return false
}

func (x *Download) GetGeoPos() bool {
	if x != nil {
		return x.GeoPos
	}
	return false
}

func (x *Download) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *Download) GetNumYears() int32 {
	if x != nil {
		return x.NumYears
	}
	return 0
}

func (x *Download) GetLatOneof() isDownload_LatOneof {
	if x != nil {
		return x.LatOneof
	}
	return nil
}

func (x *Download) GetOldLatitude() float64 {
	if x != nil {
		if x, ok := x.LatOneof.(*Download_OldLatitude); ok {
			return x.OldLatitude
		}
	}
	return 0
}

func (x *Download) GetLatitude() float32 {
	if x != nil {
		if x, ok := x.LatOneof.(*Download_Latitude); ok {
			return x.Latitude
		}
	}
	return 0
}

func (x *Download) GetLongOneof() isDownload_LongOneof {
	if x != nil {
		return x.LongOneof
	}
	return nil
}

func (x *Download) GetOldLongitude() float64 {
	if x != nil {
		if x, ok := x.LongOneof.(*Download_OldLongitude); ok {
			return x.OldLongitude
		}
	}
	return 0
}

func (x *Download) GetLongitude() float32 {
	if x != nil {
		if x, ok := x.LongOneof.(*Download_Longitude); ok {
			return x.Longitude
		}
	}
	return 0
}

func (x *Download) GetTzid() string {
	if x != nil {
		return x.Tzid
	}
	return ""
}

func (x *Download) GetStartOneof() isDownload_StartOneof {
	if x != nil {
		return x.StartOneof
	}
	return nil
}

func (x *Download) GetStartStr() string {
	if x != nil {
		if x, ok := x.StartOneof.(*Download_StartStr); ok {
			return x.StartStr
		}
	}
	return ""
}

func (x *Download) GetStart() int64 {
	if x != nil {
		if x, ok := x.StartOneof.(*Download_Start); ok {
			return x.Start
		}
	}
	return 0
}

func (x *Download) GetEndOneof() isDownload_EndOneof {
	if x != nil {
		return x.EndOneof
	}
	return nil
}

func (x *Download) GetEndStr() string {
	if x != nil {
		if x, ok := x.EndOneof.(*Download_EndStr); ok {
			return x.EndStr
		}
	}
	return ""
}

func (x *Download) GetEnd() int64 {
	if x != nil {
		if x, ok := x.EndOneof.(*Download_End); ok {
			return x.End
		}
	}
	return 0
}

func (x *Download) GetYomKippurKatan() bool {
	if x != nil {
		return x.YomKippurKatan
	}
	return false
}

func (x *Download) GetHour12() Download_Hour12 {
	if x != nil {
		return x.Hour12
	}
	return Download_UNSET
}

func (x *Download) GetCityName() string {
	if x != nil {
		return x.CityName
	}
	return ""
}

func (x *Download) GetYerushalmiYomi() bool {
	if x != nil {
		return x.YerushalmiYomi
	}
	return false
}

func (x *Download) GetNachYomi() bool {
	if x != nil {
		return x.NachYomi
	}
	return false
}

func (x *Download) GetRambam1() bool {
	if x != nil {
		return x.Rambam1
	}
	return false
}

func (x *Download) GetChofetzChaim() bool {
	if x != nil {
		return x.ChofetzChaim
	}
	return false
}

func (x *Download) GetShemiratHaLashon() bool {
	if x != nil {
		return x.ShemiratHaLashon
	}
	return false
}

func (x *Download) GetPsalms() bool {
	if x != nil {
		return x.Psalms
	}
	return false
}

func (x *Download) GetDafWeekly() bool {
	if x != nil {
		return x.DafWeekly
	}
	return false
}

func (x *Download) GetElev() int32 {
	if x != nil {
		return x.Elev
	}
	return 0
}

func (x *Download) GetUseElevation() bool {
	if x != nil {
		return x.UseElevation
	}
	return false
}

func (x *Download) GetTanakhYomi() bool {
	if x != nil {
		return x.TanakhYomi
	}
	return false
}

func (x *Download) GetPirkeiAvotSummer() bool {
	if x != nil {
		return x.PirkeiAvotSummer
	}
	return false
}

func (x *Download) GetYizkor() bool {
	if x != nil {
		return x.Yizkor
	}
	return false
}

func (x *Download) GetArukhHaShulchanYomi() bool {
	if x != nil {
		return x.ArukhHaShulchanYomi
	}
	return false
}

func (x *Download) GetYySchottenstein() bool {
	if x != nil {
		return x.YySchottenstein
	}
	return false
}

func (x *Download) GetPerekYomi() bool {
	if x != nil {
		return x.PerekYomi
	}
	return false
}

func (x *Download) GetShabbatMevarchim() bool {
	if x != nil {
		return x.ShabbatMevarchim
	}
	return false
}

func (x *Download) GetRambam3() bool {
	if x != nil {
		return x.Rambam3
	}
	return false
}

func (x *Download) GetSeferHaMitzvot() bool {
	if x != nil {
		return x.SeferHaMitzvot
	}
	return false
}

func (x *Download) GetKitzurShulchanAruch() bool {
	if x != nil {
		return x.KitzurShulchanAruch
	}
	return false
}

func (x *Download) GetMonthMode() Download_MonthMode {
	if x != nil {
		return x.MonthMode
	}
	return Download_GREGORIAN_ARABIC
}

func (x *Download) GetYomTovOnly() bool {
	if x != nil {
		return x.YomTovOnly
	}
	return false
}

func (x *Download) GetDirshuAmudYomi() bool {
	if x != nil {
		return x.DirshuAmudYomi
	}
	return false
}

func (x *Download) GetTzeit() float32 {
	if x != nil {
		return x.Tzeit
	}
	return 0
}

func (x *Download) GetNine29() bool {
	if x != nil {
		return x.Nine29
	}
	return false
}

func (x *Download) GetDirshuDafHalacha() bool {
	if x != nil {
		return x.DirshuDafHalacha
	}
	return false
}

type isDownload_LatOneof interface {
	isDownload_LatOneof()
}

type Download_OldLatitude struct {
	OldLatitude float64 `protobuf:"fixed64,32,opt,name=old_latitude,json=oldLatitude,proto3,oneof"`
}

type Download_Latitude struct {
	Latitude float32 `protobuf:"fixed32,41,opt,name=latitude,proto3,oneof"`
}

func (*Download_OldLatitude) isDownload_LatOneof() {}

func (*Download_Latitude) isDownload_LatOneof() {}

type isDownload_LongOneof interface {
	isDownload_LongOneof()
}

type Download_OldLongitude struct {
	OldLongitude float64 `protobuf:"fixed64,33,opt,name=old_longitude,json=oldLongitude,proto3,oneof"`
}

type Download_Longitude struct {
	Longitude float32 `protobuf:"fixed32,42,opt,name=longitude,proto3,oneof"`
}

func (*Download_OldLongitude) isDownload_LongOneof() {}

func (*Download_Longitude) isDownload_LongOneof() {}

type isDownload_StartOneof interface {
	isDownload_StartOneof()
}

type Download_StartStr struct {
	StartStr string `protobuf:"bytes,35,opt,name=start_str,json=startStr,proto3,oneof"`
}

type Download_Start struct {
	Start int64 `protobuf:"varint,43,opt,name=start,proto3,oneof"`
}

func (*Download_StartStr) isDownload_StartOneof() {}

func (*Download_Start) isDownload_StartOneof() {}

type isDownload_EndOneof interface {
	isDownload_EndOneof()
}

type Download_EndStr struct {
	EndStr string `protobuf:"bytes,36,opt,name=end_str,json=endStr,proto3,oneof"`
}

type Download_End struct {
	End int64 `protobuf:"varint,44,opt,name=end,proto3,oneof"`
}

func (*Download_EndStr) isDownload_EndOneof() {}

func (*Download_End) isDownload_EndOneof() {}

var File_download_proto protoreflect.FileDescriptor

const file_download_proto_rawDesc = "" +
	"\n" +
	"\x0edownload.proto\"\xe5\x11\n" +
	"\bDownload\x12\x14\n" +
	"\x05major\x18\x01 \x01(\bR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\bR\x05minor\x12 \n" +
	"\vroshChodesh\x18\x03 \x01(\bR\vroshChodesh\x12\x16\n" +
	"\x06modern\x18\x04 \x01(\bR\x06modern\x12\x1c\n" +
	"\tminorFast\x18\x05 \x01(\bR\tminorFast\x12&\n" +
	"\x0especialShabbat\x18\x06 \x01(\bR\x0especialShabbat\x12\x16\n" +
	"\x06israel\x18\a \x01(\bR\x06israel\x12$\n" +
	"\rhavdalahTzeit\x18\b \x01(\bR\rhavdalahTzeit\x12\"\n" +
	"\fisHebrewYear\x18\t \x01(\bR\fisHebrewYear\x12&\n" +
	"\x0ecandlelighting\x18\n" +
	" \x01(\bR\x0ecandlelighting\x12\x1c\n" +
	"\tgeonameid\x18\v \x01(\x05R\tgeonameid\x12\x12\n" +
	"\x04year\x18\f \x01(\x05R\x04year\x12\x16\n" +
	"\x06locale\x18\r \x01(\tR\x06locale\x12\"\n" +
	"\fhavdalahMins\x18\x0e \x01(\x05R\fhavdalahMins\x12.\n" +
	"\x12candleLightingMins\x18\x0f \x01(\x05R\x12candleLightingMins\x12\x14\n" +
	"\x05emoji\x18\x10 \x01(\bR\x05emoji\x12\x16\n" +
	"\x06sedrot\x18\x11 \x01(\bR\x06sedrot\x12\x10\n" +
	"\x03zip\x18\x12 \x01(\tR\x03zip\x12\x18\n" +
	"\ayearNow\x18\x13 \x01(\bR\ayearNow\x12\x1c\n" +
	"\tsubscribe\x18\x14 \x01(\bR\tsubscribe\x12 \n" +
	"\vaddAltDates\x18\x17 \x01(\bR\vaddAltDates\x122\n" +
	"\x14addAltDatesForEvents\x18\x18 \x01(\bR\x14addAltDatesForEvents\x12\x12\n" +
	"\x04omer\x18\x19 \x01(\bR\x04omer\x12\x18\n" +
	"\adafyomi\x18\x1a \x01(\bR\adafyomi\x12\x12\n" +
	"\x04euro\x18\x1b \x01(\bR\x04euro\x12\x1e\n" +
	"\n" +
	"mishnaYomi\x18\x1c \x01(\bR\n" +
	"mishnaYomi\x12\x16\n" +
	"\x06geoPos\x18\x1d \x01(\bR\x06geoPos\x12\x14\n" +
	"\x05month\x18\x1e \x01(\x05R\x05month\x12\x1a\n" +
	"\bnumYears\x18\x1f \x01(\x05R\bnumYears\x12#\n" +
	"\fold_latitude\x18  \x01(\x01H\x00R\voldLatitude\x12\x1c\n" +
	"\blatitude\x18) \x01(\x02H\x00R\blatitude\x12%\n" +
	"\rold_longitude\x18! \x01(\x01H\x01R\foldLongitude\x12\x1e\n" +
	"\tlongitude\x18* \x01(\x02H\x01R\tlongitude\x12\x12\n" +
	"\x04tzid\x18\" \x01(\tR\x04tzid\x12\x1d\n" +
	"\tstart_str\x18# \x01(\tH\x02R\bstartStr\x12\x16\n" +
	"\x05start\x18+ \x01(\x03H\x02R\x05start\x12\x19\n" +
	"\aend_str\x18$ \x01(\tH\x03R\x06endStr\x12\x12\n" +
	"\x03end\x18, \x01(\x03H\x03R\x03end\x12&\n" +
	"\x0eyomKippurKatan\x18% \x01(\bR\x0eyomKippurKatan\x12(\n" +
	"\x06hour12\x18' \x01(\x0e2\x10.Download.Hour12R\x06hour12\x12\x1a\n" +
	"\bcityName\x18( \x01(\tR\bcityName\x12&\n" +
	"\x0eyerushalmiYomi\x18- \x01(\bR\x0eyerushalmiYomi\x12\x1a\n" +
	"\bnachYomi\x18. \x01(\bR\bnachYomi\x12\x18\n" +
	"\arambam1\x18/ \x01(\bR\arambam1\x12\"\n" +
	"\fchofetzChaim\x180 \x01(\bR\fchofetzChaim\x12*\n" +
	"\x10shemiratHaLashon\x181 \x01(\bR\x10shemiratHaLashon\x12\x16\n" +
	"\x06psalms\x182 \x01(\bR\x06psalms\x12\x1c\n" +
	"\tdafWeekly\x183 \x01(\bR\tdafWeekly\x12\x12\n" +
	"\x04elev\x184 \x01(\x05R\x04elev\x12\"\n" +
	"\fuseElevation\x185 \x01(\bR\fuseElevation\x12\x1e\n" +
	"\n" +
	"tanakhYomi\x186 \x01(\bR\n" +
	"tanakhYomi\x12*\n" +
	"\x10pirkeiAvotSummer\x187 \x01(\bR\x10pirkeiAvotSummer\x12\x16\n" +
	"\x06yizkor\x188 \x01(\bR\x06yizkor\x120\n" +
	"\x13arukhHaShulchanYomi\x189 \x01(\bR\x13arukhHaShulchanYomi\x12(\n" +
	"\x0fyySchottenstein\x18: \x01(\bR\x0fyySchottenstein\x12\x1c\n" +
	"\tperekYomi\x18; \x01(\bR\tperekYomi\x12*\n" +
	"\x10shabbatMevarchim\x18< \x01(\bR\x10shabbatMevarchim\x12\x18\n" +
	"\arambam3\x18= \x01(\bR\arambam3\x12&\n" +
	"\x0eseferHaMitzvot\x18> \x01(\bR\x0eseferHaMitzvot\x120\n" +
	"\x13kitzurShulchanAruch\x18? \x01(\bR\x13kitzurShulchanAruch\x121\n" +
	"\tmonthMode\x18@ \x01(\x0e2\x13.Download.MonthModeR\tmonthMode\x12\x1e\n" +
	"\n" +
	"yomTovOnly\x18A \x01(\bR\n" +
	"yomTovOnly\x12&\n" +
	"\x0edirshuAmudYomi\x18B \x01(\bR\x0edirshuAmudYomi\x12\x14\n" +
	"\x05tzeit\x18C \x01(\x02R\x05tzeit\x12\x16\n" +
	"\x06nine29\x18D \x01(\bR\x06nine29\x12*\n" +
	"\x10dirshuDafHalacha\x18E \x01(\bR\x10dirshuDafHalacha\"$\n" +
	"\x06Hour12\x12\t\n" +
	"\x05UNSET\x10\x00\x12\x06\n" +
	"\x02ON\x10\x01\x12\a\n" +
	"\x03OFF\x10\x02\"G\n" +
	"\tMonthMode\x12\x14\n" +
	"\x10GREGORIAN_ARABIC\x10\x00\x12\x11\n" +
	"\rHEBREW_ARABIC\x10\x01\x12\x11\n" +
	"\rHEBREW_HEBREW\x10\x02B\v\n" +
	"\tlat_oneofB\f\n" +
	"\n" +
	"long_oneofB\r\n" +
	"\vstart_oneofB\v\n" +
	"\tend_oneofJ\x04\b&\x10'B0Z.github.com/hebcal/hebcal-api-go/pkg/downloadpbb\x06proto3"

var (
	file_download_proto_rawDescOnce sync.Once
	file_download_proto_rawDescData []byte
)

func file_download_proto_rawDescGZIP() []byte {
	file_download_proto_rawDescOnce.Do(func() {
		file_download_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_download_proto_rawDesc), len(file_download_proto_rawDesc)))
	})
	return file_download_proto_rawDescData
}

var file_download_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_download_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_download_proto_goTypes = []any{
	(Download_Hour12)(0),    // 0: Download.Hour12
	(Download_MonthMode)(0), // 1: Download.MonthMode
	(*Download)(nil),        // 2: Download
}
var file_download_proto_depIdxs = []int32{
	0, // 0: Download.hour12:type_name -> Download.Hour12
	1, // 1: Download.monthMode:type_name -> Download.MonthMode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_download_proto_init() }
func file_download_proto_init() {
	if File_download_proto != nil {
		return
	}
	file_download_proto_msgTypes[0].OneofWrappers = []any{
		(*Download_OldLatitude)(nil),
		(*Download_Latitude)(nil),
		(*Download_OldLongitude)(nil),
		(*Download_Longitude)(nil),
		(*Download_StartStr)(nil),
		(*Download_Start)(nil),
		(*Download_EndStr)(nil),
		(*Download_End)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_download_proto_rawDesc), len(file_download_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_download_proto_goTypes,
		DependencyIndexes: file_download_proto_depIdxs,
		EnumInfos:         file_download_proto_enumTypes,
		MessageInfos:      file_download_proto_msgTypes,
	}.Build()
	File_download_proto = out.File
	file_download_proto_goTypes = nil
	file_download_proto_depIdxs = nil
}
