// Dumps every event and its canonical URL from @hebcal/core, for diffing
// against the same range generated by hebcal-go.
//
//   node tools/dump-urls.mjs diaspora > /tmp/js-d.tsv
//   node tools/dump-urls.mjs il       > /tmp/js-i.tsv
//
// The Go side of the comparison lives in hebcal-go; this is the reference
// half. Running it over a century on both schedules is what found three URL
// bugs that a single year did not: Yom Kippur Katan has no page at all, a
// common year's single Adar must not be numbered adar-i, and Erev Pesach and
// Erev Sukkot were missing the IL_ONLY/CHUL_ONLY flags that decide whether a
// link carries ?i=on.
//
// Output is one TSV row per event: date, untranslated description, URL.
import {hebcalCore} from './hebcalweb.mjs';

const {HebrewCalendar, Location} = await hebcalCore();

const loc = new Location(37.44, -122.14, false, 'America/Los_Angeles', 'Palo Alto', 'US', 5380748);
const out = [];
const IL = process.argv[2] === 'il';
for (let year = 1990; year <= 2089; year++) {
  const events = HebrewCalendar.calendar({
    year, isHebrewYear: false, numYears: 1,
    candlelighting: true, location: loc, il: IL,
    sedrot: true, omer: true, molad: true, shabbatMevarchim: true,
    yomKippurKatan: true, addHebrewDates: false,
  });
  for (const ev of events) {
    const url = ev.url() || '';
    out.push([ev.getDate().greg().toISOString().slice(0, 10), ev.getDesc(), url].join('\t'));
  }
}
console.log(out.join('\n'));
