// Regenerates the month and weekday tables in locale.go.
//
//   node tools/dump-locales.mjs > /tmp/locales.json
//   node tools/dump-locales.mjs --go > internal/model/calendarnames.go
//
// hebcal-web gets these names from the dayjs locales that src/dayjs-locales.js
// imports, and maps its short `lg` codes onto them through localeMap in
// src/lang.js. Taking the strings from the same source is what keeps a German
// or Portuguese calendar reading identically in both implementations, rather
// than from a hand-typed table that drifts.
import {importFromWeb, webRoot} from './hebcalweb.mjs';

// The localeMap values from hebcal-web's src/lang.js, plus the English
// default. Transliterated locales ("s", "ashkenazi") are deliberately absent:
// their event text is Latin script, so English month names are the right
// pairing and locale.go falls back to them.
const locales = ['en', 'de', 'es', 'fi', 'fr', 'he', 'hu', 'nl', 'pl', 'pt', 'ru', 'ro', 'uk'];

const {default: dayjs} = await importFromWeb('node_modules/dayjs/dayjs.min.js');
await importFromWeb('src/dayjs-locales.js');

const out = {};
for (const lc of locales) {
  const months = [];
  const monthsShort = [];
  const weekdays = [];
  for (let m = 0; m < 12; m++) {
    // A mid-month date, so locales with declined forms give the standalone
    // spelling a page title wants.
    const d = dayjs(new Date(2026, m, 15)).locale(lc);
    months.push(d.format('MMMM'));
    monthsShort.push(d.format('MMM'));
  }
  const sunday = dayjs('2026-01-04').locale(lc); // a Sunday
  for (let i = 0; i < 7; i++) {
    weekdays.push(sunday.add(i, 'day').format('dddd'));
  }
  out[lc] = {months, monthsShort, weekdays};
}

if (!process.argv.includes('--go')) {
  console.log(JSON.stringify(out, null, 2));
  process.exit(0);
}

const list = (xs) => xs.map((x) => JSON.stringify(x)).join(', ');
const lines = [
  'package model',
  '',
  '// Month and weekday names for every locale the PDF calendars can render.',
  '//',
  '// Generated by tools/dump-locales.mjs from the dayjs locales that',
  '// src/dayjs-locales.js imports, so the strings match what the Node',
  '// implementation prints. hebcal-web maps its short `lg` codes onto these',
  '// through localeMap in src/lang.js; model.AliasLocale does the same, and',
  '// namesByLocale below is keyed by the result.',
  '',
  '',
  'import "strings"',
  '',
  '// CalendarNames holds the localized vocabulary for one language.',
  'type CalendarNames struct {',
  '\t// Months are the full Gregorian month names used in a page title.',
  '\tMonths [12]string',
  '\t// MonthsShort are the abbreviated names used in the Gregorian date range',
  '\t// beneath a Hebrew-month title.',
  '\tMonthsShort [12]string',
  '\t// Weekdays are the column headings, Sunday first.',
  '\tWeekdays [7]string',
  '}',
  '',
  '// namesByLocale is keyed by the resolved locale name, not by the short `lg`',
  '// code. Locales absent here fall back to English, which is what hebcal-web',
  '// does for its transliterated locales (`s`, `ashkenazi`): their output is',
  '// Latin script, so English month names are the right pairing.',
  'var namesByLocale = map[string]CalendarNames{',
];
for (const lc of locales) {
  const v = out[lc];
  lines.push(`\t${JSON.stringify(lc)}: {`);
  lines.push(`\t\tMonths:      [12]string{${list(v.months)}},`);
  lines.push(`\t\tMonthsShort: [12]string{${list(v.monthsShort)}},`);
  lines.push(`\t\tWeekdays:    [7]string{${list(v.weekdays)}},`);
  lines.push('\t},');
}
lines.push('}');
lines.push('');
lines.push('// NamesFor returns the calendar vocabulary for a resolved locale, falling');
lines.push('// back to English. The lookup is case-insensitive, and he-x-nonikud shares');
lines.push("// he's month and weekday names -- hebcal-web's localeMap resolves both to the");
lines.push('// same dayjs `he` locale, since the no-nikud variant only affects event');
lines.push('// subjects.');
lines.push('func NamesFor(locale string) CalendarNames {');
lines.push('\tkey := strings.ToLower(locale)');
lines.push('\tif key == "he-x-nonikud" {');
lines.push('\t\tkey = "he"');
lines.push('\t}');
lines.push('\tif n, ok := namesByLocale[key]; ok {');
lines.push('\t\treturn n');
lines.push('\t}');
lines.push('\treturn namesByLocale["en"]');
lines.push('}');
console.error(`generated from ${webRoot}; pipe to internal/model/calendarnames.go and run gofmt`);
console.log(lines.join('\n'));
